Create employee components #34
DataByne/uraPointOfSale pull request #97
Opened 2019-10-28 06:25 UTC by peterle08

2019-10-28 13:29 UTC, kyletpugh commented on src/app/edit-employee/edit-employee.component.spec.ts
> +import { async, ComponentFixture, TestBed } from '@angular/core/testing';
These .spec.ts files are unnecessary, they are for testing using jasmine and we are using cucumber.

2019-10-28 13:31 UTC, kyletpugh commented on src/app/edit-employee/edit-employee.component.html
> +
This should be basically the same as edit employee but already populated with a remove/delete option, you could have probably reused the same component with query parameters.

2019-10-28 13:32 UTC, kyletpugh commented on src/app/insert-employee/insert-employee.component.spec.ts
> +import { async, ComponentFixture, TestBed } from '@angular/core/testing';
Unnecessary file for the same reason as the other .spec.ts files.

2019-10-28 13:33 UTC, kyletpugh commented on src/app/list-employee/list-employee.component.html
> +
Why is the list employees not the page that lists all the current employees and has an option to add a new employee? This should be the add employee content.

2019-10-28 13:33 UTC, kyletpugh commented on src/app/list-employee/list-employee.component.spec.ts
> +import { async, ComponentFixture, TestBed } from '@angular/core/testing';
Unnecessary file for the same reason as all the other .spec.ts files.

2019-10-28 13:35 UTC, kyletpugh commented on src/app/app.module.ts
> +  { path:'insert_employee', component:InsertEmployeeComponent },
This should be `path: 'employees/add'

2019-10-28 13:36 UTC, kyletpugh commented on src/app/app.module.ts
> +  { path:'list_employee', component:ListEmployeeComponent },
This should be `path: 'employees'`

2019-10-28 13:36 UTC, kyletpugh commented on src/app/app.module.ts
> +  { path:'edit_employee', component:EditEmployeeComponent},
This should be `path: 'employees/edit'`

2019-10-28 13:37 UTC, kyletpugh requested changes
Where is the list of employees? The employees does not belong in the header, and should link to employees list not adding an employee. The edit employee does not correctly navigate and is not correct, you need to be able to edit the same attributes as when they were added, but also be able to remove the user, why enter the employee id twice to do so? Just make a remove/delete button and popup a confirmation. You need to fix these things before the pull request is approved.

2019-10-28 13:44 UTC, kyletpugh commented on src/app/insert-employee/insert-employee.component.html
> +                <option value = "O">Others</option>
You may want to add a custom option instead that allows the person to enter their own gender, or find a comprehensive list.

2019-10-29 03:02 UTC, kyletpugh approved these changes

2019-10-29 03:03 UTC, RyanYoak approved these changes

2019-10-29 03:04 UTC, merged